### ISSUE TITLE
Geen check of object al is toegevoegd

### ISSUE THREAD

**Issue by ralphniels** [HANICA/oopg#10]
Bij addGameObject wordt niet gecontroleerd of het object niet al is toegevoegd. Dit heeft als gevolg dat de update van een object bij meermaals toevoegen ook meermaals wordt uitgevoerd. De snelheid wordt daarmee bijv. ook (aantalkeertoegevoegd-1) keer zo hoog.

**Comment by bartvanderwal** [comment]
De add methode checkt het nu. Ik heb `Vector` even laten zitten.

In geval van adden zou je nu niks kunnen doen, maar het lijkt me het netst om een exceptie te gooien, want games moeten zelf zorgen dat ze objecten niet dubbel toevoegen, want dit is functioneel niet nuttig (en was dus slecht voor de performance).
Ik heb hier een RuntimeException van gemaakt, zodat het geen checked exception wordt. Want je wilt sowieso niet dat studenten deze gaan `catch`en (maar direct hun code aanpassen).

In kader van best practice van gebruik 'specific' exceptions heb ik een nieuwe subclass van gemaakt, maar wel ietwat generieke, GameEngineRuntimeException, want een klasse voor enkel deze check leek me over kill. Ik heb ook netjes een unit test gemaakt, waarin deze specifieke exception wordt verwacht bij 2e keer toevoegen van zelfde item.

Pull request staat open.

**Comment by bartvanderwal** [comment]
Top!
Lokaal even geuodate en getest maar alles lijkt te werken en met mijn update coor #10. Je hebt opsplitsen submodules engine en waterworld weer teruggedraaid zie ik/begrijp ik.

**Comment by meronbrouwer** [comment]
ja klopt. waterworld heeft nu een eigen project. vokgende week eennkewrtje afstemmen?

**Comment by bartvanderwal** [comment]
Nee ik moet tijd even vrijhouden i.v.m. andere deadline.

Ik probeer losse Waterworld zelf een keer aan de praat te krijgen.

Ik pak nog een of twee losse items op, en check tutorials samen met Fritz en nog wat bijwerken.

Voor meer heb ik eigenlijk geen uren meer qua OOPD/-G…

Ik heb Yakup wel gevraagd of hij ook nog 1 of 2 issues kon doen.

We kunnen wel keer overleggen over OOSE. Ik heb gisteren onderwijsonline doorlopen, gaf ook nog wat vraagtekens.
Hoe zit het precies met eduscrum? En wat is EAI? ☺

Goed weekend!
