### ISSUE TITLE
README uitbreiden met hoe aan de praat te krijgen :)

### ISSUE THREAD

**Issue by bartvanderwal** [HANICA/oopg#12]
Ik ben een relatieve Java/Eclipse leek.
Ik mis in de `README.md` een how-to beschrijving hoe ik OOPG kan runnen.

**Comment by meronbrouwer** [comment]
Deze ga ik oppakken en zal samenhangen met de manier waarop we de applicatie gaan bundelen. de huidige manier van een zipje met daarin een eclipse project lijkt mij niet de wenselijke manier.

**Comment by bartvanderwal** [comment]
@meron geldt nog steeds?

Voor nu zouden we ook met volgende screenshots iets kunnen doen
<img width="267" alt="eclipse-3" src="https://user-images.githubusercontent.com/3029472/40170030-c48446f6-59c7-11e8-9e74-d9e1a737bb3d.png">
![eclipse-2](https://user-images.githubusercontent.com/3029472/40170031-c49d996c-59c7-11e8-922c-4e4c0ccf9815.png)
![eclipse](https://user-images.githubusercontent.com/3029472/40170032-c4b53f40-59c7-11e8-853e-382ea1d9549d.png)
![git-download](https://user-images.githubusercontent.com/3029472/40170033-c4ce6218-59c7-11e8-95a9-1d125786ea92.png)

**Comment by bartvanderwal** [comment]
Ik heb bovenstaande screenshots met toelichting nu ingevoegd in de README.

@meron kun jij dit dan eventueel - zo nodig - aanpassen voor huidige situatie waarin waterworld en de engine aparte Maven 'submodules' in hun eigen root folder zijn.

Wellicht moet dit 'how-to-run' ook verplaatst naar een aparte `.md` buiten de `README.md`, met een linkje ernaar in README.

**Comment by meronbrouwer** [comment]
Dit is nu meer van toepassing op het waterworld project. Ik heb daar ook in de readme opgenomen hoe de applicatie geïmporteerd en gerund moet worden. Nog zonder screenshots.
