### ISSUE TITLE
volledige .jar beschikbaar maken

### ISSUE THREAD

**Issue by ysbakker** [HANICA/oopg#17]
Ik denk dat het handiger is om het volledige .jar bestand (inclusief Processing, ddf en natuurlijk de oopg engine) in de github repo te zetten (of op een andere plek hosten) zodat studenten deze gemakkelijk kunnen downloaden.
Het is wel mogelijk via Maven (zoals het waterworld project doet) maar niet erg voor de hand liggend, en voor zover ik weet lastig in eclipse. Ook is het importeren van een map als library (in ieder geval binnen IntelliJ) vrij complex en zou het dus een stuk makkelijker zijn om de hele .jar in een keer te kunnen importeren, zoals we in de lesstof ook leren met processing.core.

**Comment by bartvanderwal** [comment]
@meronbrouwer Hoi Meron,
Zou jij hier naar willen kijken of op willen reageren?
Ik heb eerlijk gezegd ook nog niet de tijd genomen om fritz' tutorials door te nemen of OOPG en/of Waterworld op de nieuwe manier aan de praat te krijgen.

**Comment by meronbrouwer** [comment]
ha bart, dat kan prima. ik zal er deze week ff naar kijken.

Op wo 13 mrt. 2019 14:47 schreef Bart van der Wal <notifications@github.com

**Comment by meronbrouwer** [comment]
De jar is beschikbaar in de gh-pages branch en wordt na iedere built opnieuw gemaakt en gedeployed.

Vanaf p3 zullen we de nieuwe Engine gaan inzetten, dus de ontwikkeling aan oopg ligt stil.
