### ISSUE TITLE
De wiki klopt voor geen meter

### ISSUE THREAD

**Issue by wessltov** [HANICA/oopg#20]
Probeer eens stap voor stap door de wiki heen te lopen. Ga je gang, probeer maar.

- Het springt van de hak op de tak.
- De code klopt in veel gevallen niet.
- Hele onderwerpen lijken overgeslagen.

De wiki is voor eerstejaars studenten het eerste punt van informatie-inwinning. Het lijkt mij dan niet de bedoeling als de 12-delige tutorial vol staat met fouten.

**Comment by jakorten** [comment]
Is echt geweldig aan Git dat je heel precies aan kunt geven wat wel/niet issues zijn ;) just a tip @wessltov

**Comment by wessltov** [comment]
Mijn welgemeende excuses. Ik heb een deadline en te weinig tijd

**Comment by jakorten** [comment]
Tsja, te weinig tijd is altijd een slecht excuus, (let wel: het past niet in mijn planning is natuurlijk wel legitiem), vermoedelijk was dat laatste ook de reden waarom docenten het nog niet konden optimaliseren gok ik zo ;)

**Comment by wessltov** [comment]
> De engine werd in 2014-2015 ontwikkeld door een aantal OOSE-studenten en wordt momenteel doorontwikkeld door docenten en studenten van ICA.

Oftewel, genoeg tijd om iemand naar die wiki te laten kijken.

**Comment by bartvanderwal** [comment]
Graag issues concreter aangeven dan 'klopt voor geen meter'.
Bijvoorbeeld: In [tutorial 2](https://github.com/HANICA/oopg/wiki/02-Sprites-gebruiken) staat `dit en dat`. Ik verwacht `zus en zo`.

-> **closed**
