### ISSUE TITLE
Geen Licentie aanwezig 

### ISSUE THREAD

**Issue by RyanAelen** [HANICA/oopg#23]
Er is geen licentie in de repo, waardoor het reproduceren, verspreiden of er afgeleide werken van maken niet is toegestaan.

**Comment by RyanAelen** [comment]
Wegen het niet aanwezig zijn van licentie, kan er geen aanpassingen en verbeterginen worden toegepast.

**Comment by bartvanderwal** [comment]
Hoi Ryan,

Dank voor je opmerking, maar dit klopt niet geheel. Door het ontbreken van licentie in deze repo hoort het werk standaard toe aan de auteur(s). Zo staat dit in de (Nederlandse) wet. Daarmee is commercieel toepassen inderdaad niet toegestaan zonder toestemming van deze auteurs, zoals wel mag bij MIT license e.d. Die vrijwaren zich dan weer van schadeclaims als gevolg van dit gebruik. 

Gezien de achtergrond is oopg wel prima te gebruiken voor educatieve doeleinden, zoals het maken van de game benodigd om OOPD af te sluiten. Daarbinnen is het prima mogelijk om bugs te melden en verbetersuggesties te doen. En zelfs pull requests met al verbeterde versie.

Heb je een idee hiervoor? Op zich staat er een nieuwe game engine op de stoep, dus daar gaat energie nu meer naar toe dan naar oopg, maar suggesties zijn altijd welkom. Verdere beperkingen en drempels van OOPG moet je je tijdens opdracht zien op te lossen, dat is de afgelopen jaren heel erg veel studenten gelukt.

**Comment by RyanAelen** [comment]
Dank u Bart voor het antwoorden,

Heb dan twee vragen.
1. Is er al een publieke repo beschikbaar voor de nieuwe engine?
2. Waar kan ik update's krijgen betreft de nieuwe engine?

**Comment by meronbrouwer** [comment]
https://github.com/han-yaeger/yaeger

**Comment by meronbrouwer** [comment]
Merk wel op dat yaeger nog een beta release is en er mogelijk nog features ontbreken. Pas in p3 zal de eerste niet-beta verschijnen.
